PREFIX : <>

SELECT ?planet ?orbital_period
FROM :CurrentWorldDataCollectorMt-NonHomocentric
WHERE {
	?g :genlMt :EarthObservationalAstronomyMt .
	GRAPH ?g { 
		?planet a :Planet ; 
			:orbits :TheSun ;
			:orbitalPeriod ?orbital_period
	}
	?planet a :DwarfPlanet
}
