PREFIX : <>

SELECT ?planet ?orbital_period
FROM :UniverseDataMt
WHERE {
	GRAPH :UniverseDataMt { 
		?planet a :Planet ; 
			:orbits :TheSun ;
			:orbitalPeriod ?orbital_period
	FILTER (NOT EXISTS { ?planet a :DwarfPlanet })
	}
}
