PREFIX : <>

SELECT ?planet ?orbital_period
FROM :CurrentWorldDataCollectorMt-NonHomocentric
WHERE {
	?planet a :Planet ; 
		:orbits :TheSun ;
		:orbitalPeriod ?orbital_period
	FILTER (NOT EXISTS { ?planet a :DwarfPlanet })
}